// Package testutil provides helpers for loading and using test fixtures
// generated by the Python cross-validation harness.
package testutil

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// FixtureFile represents a generated fixture file.
type FixtureFile struct {
	Generator    string     `json:"generator"`
	PgmpyVersion string     `json:"pgmpy_version"`
	TestCases    []TestCase `json:"test_cases"`
}

// TestCase represents a single test case with input and expected output.
type TestCase struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Input       json.RawMessage `json:"input"`
	Expected    json.RawMessage `json:"expected"`
}

// fixturesRoot returns the absolute path to tests/fixtures/.
func fixturesRoot() string {
	_, filename, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(filename), "..", "fixtures")
}

// loadFixtureData reads and parses a fixture file from the given absolute path.
// It returns the parsed FixtureFile or an error.
func loadFixtureData(fullPath string) (*FixtureFile, error) {
	data, err := os.ReadFile(fullPath)
	if err != nil {
		return nil, err
	}
	var ff FixtureFile
	if err := json.Unmarshal(data, &ff); err != nil {
		return nil, err
	}
	return &ff, nil
}

// LoadFixtures loads all test cases from a fixture file for a given package.
// The path is relative to tests/fixtures/, e.g., "models/fixtures.json".
func LoadFixtures(t testing.TB, path string) *FixtureFile {
	t.Helper()

	fullPath := filepath.Join(fixturesRoot(), path)
	ff, err := loadFixtureData(fullPath)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skipf("fixture file not found: %s (run 'go generate' to create)", fullPath)
			return nil
		}
		t.Fatalf("failed to parse fixture file %s: %v", path, err)
	}

	return ff
}

// FindTestCase returns the test case with the given name, or skips the test.
func (ff *FixtureFile) FindTestCase(t testing.TB, name string) *TestCase {
	t.Helper()

	for i := range ff.TestCases {
		if ff.TestCases[i].Name == name {
			return &ff.TestCases[i]
		}
	}

	t.Skipf("test case %q not found in fixtures", name)
	return nil
}

// unmarshalRawJSON unmarshals a json.RawMessage into the given target.
func unmarshalRawJSON(raw json.RawMessage, v any) error {
	return json.Unmarshal(raw, v)
}

// UnmarshalInput unmarshals the test case input into the given struct.
func (tc *TestCase) UnmarshalInput(t testing.TB, v any) {
	t.Helper()
	if err := unmarshalRawJSON(tc.Input, v); err != nil {
		t.Fatalf("failed to unmarshal input for %q: %v", tc.Name, err)
	}
}

// UnmarshalExpected unmarshals the test case expected output into the given struct.
func (tc *TestCase) UnmarshalExpected(t testing.TB, v any) {
	t.Helper()
	if err := unmarshalRawJSON(tc.Expected, v); err != nil {
		t.Fatalf("failed to unmarshal expected for %q: %v", tc.Name, err)
	}
}
