// Package testutil provides helpers for loading and using test fixtures
// generated by the Python cross-validation harness.
package testutil

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// FixtureFile represents a generated fixture file.
type FixtureFile struct {
	Generator    string     `json:"generator"`
	PgmpyVersion string    `json:"pgmpy_version"`
	GeneratedAt  string    `json:"generated_at"`
	TestCases    []TestCase `json:"test_cases"`
}

// TestCase represents a single test case with input and expected output.
type TestCase struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Input       json.RawMessage `json:"input"`
	Expected    json.RawMessage `json:"expected"`
}

// fixturesRoot returns the absolute path to tests/fixtures/.
func fixturesRoot() string {
	_, filename, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(filename), "..", "fixtures")
}

// LoadFixtures loads all test cases from a fixture file for a given package.
// The path is relative to tests/fixtures/, e.g., "models/fixtures.json".
func LoadFixtures(t *testing.T, path string) *FixtureFile {
	t.Helper()

	fullPath := filepath.Join(fixturesRoot(), path)
	data, err := os.ReadFile(fullPath)
	if err != nil {
		t.Skipf("fixture file not found: %s (run 'go generate' to create)", fullPath)
		return nil
	}

	var ff FixtureFile
	if err := json.Unmarshal(data, &ff); err != nil {
		t.Fatalf("failed to parse fixture file %s: %v", path, err)
	}

	return &ff
}

// FindTestCase returns the test case with the given name, or skips the test.
func (ff *FixtureFile) FindTestCase(t *testing.T, name string) *TestCase {
	t.Helper()

	for i := range ff.TestCases {
		if ff.TestCases[i].Name == name {
			return &ff.TestCases[i]
		}
	}

	t.Skipf("test case %q not found in fixtures", name)
	return nil
}

// UnmarshalInput unmarshals the test case input into the given struct.
func (tc *TestCase) UnmarshalInput(t *testing.T, v any) {
	t.Helper()
	if err := json.Unmarshal(tc.Input, v); err != nil {
		t.Fatalf("failed to unmarshal input for %q: %v", tc.Name, err)
	}
}

// UnmarshalExpected unmarshals the test case expected output into the given struct.
func (tc *TestCase) UnmarshalExpected(t *testing.T, v any) {
	t.Helper()
	if err := json.Unmarshal(tc.Expected, v); err != nil {
		t.Fatalf("failed to unmarshal expected for %q: %v", tc.Name, err)
	}
}
